### ISSUE TITLE
数据集可否公开下

### ISSUE THREAD

**Issue by chenlheng** [toughtwice/node2vec#1]
感谢老哥的代码！我在node2vec、deepwalk原始代码里找不到evaluation的方法，原文里又没有说清楚他们是怎么做的，多亏你的代码！点一颗star表示感谢~
不过我想问下，目前的实验设置能实现论文里的state-of-the-art吗？另外论文里的ppi和wikipedia数据库如果可以的话能公开下吗？

**Comment by toughtwice** [comment]
别的数据集没研究，在facebook数据集上边预测的auc_roc非常高

**Comment by chenlheng** [comment]
好的，谢谢了！
